name: run pre-commit checks
description: run all pre-commit managed checks
inputs:
  pre-commit-home:
    description: cache dir to use
    required: true
    default: ${{ github.workspace }}/.pre-commit-cache
runs:
  using: "composite"
  steps:
    - id: python-interpreter-hash
      shell: bash
      run: echo "HASH=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      with:
        path: ${{ inputs.pre-commit-home }}
        key: pre-commit|${{ steps.python-interpreter-hash.outputs.HASH }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run commit checks
      shell: bash
      env:
        PRE_COMMIT_HOME: ${{ inputs.pre-commit-home }}
      run: pre-commit run -a
