#!/bin/bash

set -e

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Bootstrap the dependencies of the project.
"
}

if [ "${1:-}" = "--help" ]; then
    usage
else
    pip install poetry;
    poetry install --with dev;
fi
