#!/bin/bash

set -e

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Start the application including the backend.
"
}

if [ "${1:-}" = "--help" ]; then
    usage
else
    poetry run pytest "$@"
fi
