#!/bin/bash

set -e

function usage() {
    echo -n \
        "Usage: $(basename "$0") [--nox]
Run the test suite using pytest, optionally using nox
"
}

if [ "${1:-}" = "--help" ]; then
    usage
    exit 0
fi

if [ "${1:-}" = "--nox" ]; then
    poetry run nox
else
    poetry run pytest "$@"
fi
