name: PR Checks

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry==1.7.1
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Sync
        run: uv sync
      - name: Install dependencies
        run: poetry install --with=dev
      - name: Execute linters & type checkers
        if: ${{ matrix.python-version == 3.12 }}
        run: uv run pre-commit run --all-files
      - name: Run tests
        run: poetry run nox
